// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/history.proto

package historypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type History struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid   int64  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Movieid  int64  `protobuf:"varint,2,opt,name=movieid,proto3" json:"movieid,omitempty"`
	Progress string `protobuf:"bytes,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Like     bool   `protobuf:"varint,4,opt,name=like,proto3" json:"like,omitempty"`
}

func (x *History) Reset() {
	*x = History{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{0}
}

func (x *History) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *History) GetMovieid() int64 {
	if x != nil {
		return x.Movieid
	}
	return 0
}

func (x *History) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

func (x *History) GetLike() bool {
	if x != nil {
		return x.Like
	}
	return false
}

type CreateHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History *History `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"` // History id blank
}

func (x *CreateHistoryReq) Reset() {
	*x = CreateHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryReq) ProtoMessage() {}

func (x *CreateHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryReq.ProtoReflect.Descriptor instead.
func (*CreateHistoryReq) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHistoryReq) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

type CreateHistoryRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History *History `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"` // History id filled in
}

func (x *CreateHistoryRes) Reset() {
	*x = CreateHistoryRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHistoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryRes) ProtoMessage() {}

func (x *CreateHistoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryRes.ProtoReflect.Descriptor instead.
func (*CreateHistoryRes) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHistoryRes) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

type UpdateHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History *History `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
}

func (x *UpdateHistoryReq) Reset() {
	*x = UpdateHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryReq) ProtoMessage() {}

func (x *UpdateHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryReq.ProtoReflect.Descriptor instead.
func (*UpdateHistoryReq) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateHistoryReq) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

type UpdateHistoryRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History *History `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
}

func (x *UpdateHistoryRes) Reset() {
	*x = UpdateHistoryRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHistoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryRes) ProtoMessage() {}

func (x *UpdateHistoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryRes.ProtoReflect.Descriptor instead.
func (*UpdateHistoryRes) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateHistoryRes) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

type ReadHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadHistoryReq) Reset() {
	*x = ReadHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadHistoryReq) ProtoMessage() {}

func (x *ReadHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadHistoryReq.ProtoReflect.Descriptor instead.
func (*ReadHistoryReq) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{5}
}

func (x *ReadHistoryReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadHistoryRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History *History `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
}

func (x *ReadHistoryRes) Reset() {
	*x = ReadHistoryRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadHistoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadHistoryRes) ProtoMessage() {}

func (x *ReadHistoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadHistoryRes.ProtoReflect.Descriptor instead.
func (*ReadHistoryRes) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{6}
}

func (x *ReadHistoryRes) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

type DeleteHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteHistoryReq) Reset() {
	*x = DeleteHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHistoryReq) ProtoMessage() {}

func (x *DeleteHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHistoryReq.ProtoReflect.Descriptor instead.
func (*DeleteHistoryReq) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteHistoryReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteHistoryRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteHistoryRes) Reset() {
	*x = DeleteHistoryRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHistoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHistoryRes) ProtoMessage() {}

func (x *DeleteHistoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHistoryRes.ProtoReflect.Descriptor instead.
func (*DeleteHistoryRes) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteHistoryRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListHistoriesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHistoriesReq) Reset() {
	*x = ListHistoriesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHistoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoriesReq) ProtoMessage() {}

func (x *ListHistoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoriesReq.ProtoReflect.Descriptor instead.
func (*ListHistoriesReq) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{9}
}

type ListHistoriesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History *History `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
}

func (x *ListHistoriesRes) Reset() {
	*x = ListHistoriesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHistoriesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoriesRes) ProtoMessage() {}

func (x *ListHistoriesRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoriesRes.ProtoReflect.Descriptor instead.
func (*ListHistoriesRes) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{10}
}

func (x *ListHistoriesRes) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

var File_proto_history_proto protoreflect.FileDescriptor

var file_proto_history_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x6b,
	0x0a, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x22, 0x3e, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x2a, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x3e, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x12,
	0x2a, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x3e, 0x0a, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x2a, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x3e, 0x0a, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x12,
	0x2a, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x20, 0x0a, 0x0e, 0x52,
	0x65, 0x61, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a,
	0x0e, 0x52, 0x65, 0x61, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x12,
	0x2a, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x22, 0x0a, 0x10, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x2c, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x12, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x22, 0x3e, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x32, 0xee, 0x02, 0x0a, 0x0e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0b, 0x52,
	0x65, 0x61, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x17, 0x2e, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x0d,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x2e,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x73, 0x12, 0x19, 0x2e, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x30, 0x01, 0x42, 0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x2d, 0x41, 0x64, 0x76, 0x61, 0x6e,
	0x63, 0x65, 0x64, 0x2d, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x42, 0x69, 0x6e,
	0x67, 0x65, 0x42, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2d, 0x57, 0x61, 0x74, 0x63, 0x68, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_history_proto_rawDescOnce sync.Once
	file_proto_history_proto_rawDescData = file_proto_history_proto_rawDesc
)

func file_proto_history_proto_rawDescGZIP() []byte {
	file_proto_history_proto_rawDescOnce.Do(func() {
		file_proto_history_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_history_proto_rawDescData)
	})
	return file_proto_history_proto_rawDescData
}

var file_proto_history_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_history_proto_goTypes = []interface{}{
	(*History)(nil),          // 0: history.History
	(*CreateHistoryReq)(nil), // 1: history.CreateHistoryReq
	(*CreateHistoryRes)(nil), // 2: history.CreateHistoryRes
	(*UpdateHistoryReq)(nil), // 3: history.UpdateHistoryReq
	(*UpdateHistoryRes)(nil), // 4: history.UpdateHistoryRes
	(*ReadHistoryReq)(nil),   // 5: history.ReadHistoryReq
	(*ReadHistoryRes)(nil),   // 6: history.ReadHistoryRes
	(*DeleteHistoryReq)(nil), // 7: history.DeleteHistoryReq
	(*DeleteHistoryRes)(nil), // 8: history.DeleteHistoryRes
	(*ListHistoriesReq)(nil), // 9: history.ListHistoriesReq
	(*ListHistoriesRes)(nil), // 10: history.ListHistoriesRes
}
var file_proto_history_proto_depIdxs = []int32{
	0,  // 0: history.CreateHistoryReq.history:type_name -> history.History
	0,  // 1: history.CreateHistoryRes.history:type_name -> history.History
	0,  // 2: history.UpdateHistoryReq.history:type_name -> history.History
	0,  // 3: history.UpdateHistoryRes.history:type_name -> history.History
	0,  // 4: history.ReadHistoryRes.history:type_name -> history.History
	0,  // 5: history.ListHistoriesRes.history:type_name -> history.History
	1,  // 6: history.HistoryService.CreateHistory:input_type -> history.CreateHistoryReq
	5,  // 7: history.HistoryService.ReadHistory:input_type -> history.ReadHistoryReq
	3,  // 8: history.HistoryService.UpdateHistory:input_type -> history.UpdateHistoryReq
	7,  // 9: history.HistoryService.DeleteHistory:input_type -> history.DeleteHistoryReq
	9,  // 10: history.HistoryService.ListHistorys:input_type -> history.ListHistoriesReq
	2,  // 11: history.HistoryService.CreateHistory:output_type -> history.CreateHistoryRes
	6,  // 12: history.HistoryService.ReadHistory:output_type -> history.ReadHistoryRes
	4,  // 13: history.HistoryService.UpdateHistory:output_type -> history.UpdateHistoryRes
	8,  // 14: history.HistoryService.DeleteHistory:output_type -> history.DeleteHistoryRes
	10, // 15: history.HistoryService.ListHistorys:output_type -> history.ListHistoriesRes
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_history_proto_init() }
func file_proto_history_proto_init() {
	if File_proto_history_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_history_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*History); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHistoryRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHistoryRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadHistoryRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHistoryRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHistoriesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHistoriesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_history_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_history_proto_goTypes,
		DependencyIndexes: file_proto_history_proto_depIdxs,
		MessageInfos:      file_proto_history_proto_msgTypes,
	}.Build()
	File_proto_history_proto = out.File
	file_proto_history_proto_rawDesc = nil
	file_proto_history_proto_goTypes = nil
	file_proto_history_proto_depIdxs = nil
}
